export const FETCH_PRODUCT_POPULER_1688 = "FETCH_PRODUCT_POPULER_1688";
export const FETCH_PRODUCT_POPULER_TAOBAO = "FETCH_PRODUCT_POPULER_TAOBAO";
export const CHANGE_TYPE_SEARCH = "CHANGE_TYPE_SEARCH";
